version: '2'

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - 5455:5432
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=postgresDB