version: '2'

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - 5455:5432
    environment:
      - POSTGRES_USER=employee-profile
      - POSTGRES_PASSWORD=6PsA9e6JunuHdQ2vrWE7
      - POSTGRES_DB=employee-profile
volumes:
  pgdata:
