auth0:
  audience: https://employee-profile.com/api
  domain: dev-0knqdj3ruz2l8l5k.us.auth0.com
  clientId: xIyeMQEZSoYIlDwIuAksA9LJ3qXNF2RT
spring:
  datasource:
    url: jdbc:postgresql://pg-admin-service.pg-admin:5432/employee-profile
    username: employee-profile
    password: 6PsA9e6JunuHdQ2vrWE7
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
  flyway:
    locations: /db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-0knqdj3ruz2l8l5k.us.auth0.com/
          audiences:
            - https://employee-profile.com/api
mybatis:
  type-handlers-package: com.sourcery.employeeProfile.mybatis
  type-aliases-package: com.sourcery.employeeProfile.mybatis
  configuration:
    map-underscore-to-camel-case: true
