spring:
  datasource:
    url: jdbc:postgresql://localhost:5455/employee-profile
    username: employee-profile
    password: 6PsA9e6JunuHdQ2vrWE7
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
  flyway:
    locations: /db/migration
mybatis:
  type-handlers-package: com.sourcery.employeeProfile.mybatis
  type-aliases-package: com.sourcery.employeeProfile.mybatis
  configuration:
    map-underscore-to-camel-case: true




