spring:
  datasource:
    url: jdbc:postgresql://localhost:5455/db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
mybatis:
  type-handlers-package: com.sourcery.employeeProfile.mybatis
  type-aliases-package: com.sourcery.employeeProfile.mybatis
  annotationClass: org.springframework.boot.mybatis.autoconfigure.Mapper
  configuration:
    map-underscore-to-camel-case: true




