auth0:
  audience: https://employee-profile.com/api
  domain: dev-0knqdj3ruz2l8l5k.us.auth0.com
  clientId: xIyeMQEZSoYIlDwIuAksA9LJ3qXNF2RT
spring:
  datasource:
    url: jdbc:postgresql://localhost:5455/db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-0knqdj3ruz2l8l5k.us.auth0.com/
          audiences:
            - https://employee-profile.com/api