spring:
  datasource:
    url: jdbc:postgresql://localhost:5455/db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
